/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyticsUsageRouteImport } from './routes/api/analytics/usage'
import { Route as ApiAdminUploadKnowledgeRouteImport } from './routes/api/admin/upload-knowledge'
import { Route as ApiAdminIngestedDocumentsRouteImport } from './routes/api/admin/ingested-documents'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsUsageRoute = ApiAnalyticsUsageRouteImport.update({
  id: '/api/analytics/usage',
  path: '/api/analytics/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadKnowledgeRoute = ApiAdminUploadKnowledgeRouteImport.update({
  id: '/api/admin/upload-knowledge',
  path: '/api/admin/upload-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIngestedDocumentsRoute =
  ApiAdminIngestedDocumentsRouteImport.update({
    id: '/api/admin/ingested-documents',
    path: '/api/admin/ingested-documents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/worker': typeof WorkerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/admin/ingested-documents': typeof ApiAdminIngestedDocumentsRoute
  '/api/admin/upload-knowledge': typeof ApiAdminUploadKnowledgeRoute
  '/api/analytics/usage': typeof ApiAnalyticsUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/worker': typeof WorkerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/admin/ingested-documents': typeof ApiAdminIngestedDocumentsRoute
  '/api/admin/upload-knowledge': typeof ApiAdminUploadKnowledgeRoute
  '/api/analytics/usage': typeof ApiAnalyticsUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/worker': typeof WorkerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/admin/ingested-documents': typeof ApiAdminIngestedDocumentsRoute
  '/api/admin/upload-knowledge': typeof ApiAdminUploadKnowledgeRoute
  '/api/analytics/usage': typeof ApiAnalyticsUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manager'
    | '/worker'
    | '/api/chat'
    | '/api/admin/ingested-documents'
    | '/api/admin/upload-knowledge'
    | '/api/analytics/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manager'
    | '/worker'
    | '/api/chat'
    | '/api/admin/ingested-documents'
    | '/api/admin/upload-knowledge'
    | '/api/analytics/usage'
  id:
    | '__root__'
    | '/'
    | '/manager'
    | '/worker'
    | '/api/chat'
    | '/api/admin/ingested-documents'
    | '/api/admin/upload-knowledge'
    | '/api/analytics/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagerRoute: typeof ManagerRoute
  WorkerRoute: typeof WorkerRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAdminIngestedDocumentsRoute: typeof ApiAdminIngestedDocumentsRoute
  ApiAdminUploadKnowledgeRoute: typeof ApiAdminUploadKnowledgeRoute
  ApiAnalyticsUsageRoute: typeof ApiAnalyticsUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/usage': {
      id: '/api/analytics/usage'
      path: '/api/analytics/usage'
      fullPath: '/api/analytics/usage'
      preLoaderRoute: typeof ApiAnalyticsUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-knowledge': {
      id: '/api/admin/upload-knowledge'
      path: '/api/admin/upload-knowledge'
      fullPath: '/api/admin/upload-knowledge'
      preLoaderRoute: typeof ApiAdminUploadKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ingested-documents': {
      id: '/api/admin/ingested-documents'
      path: '/api/admin/ingested-documents'
      fullPath: '/api/admin/ingested-documents'
      preLoaderRoute: typeof ApiAdminIngestedDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagerRoute: ManagerRoute,
  WorkerRoute: WorkerRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAdminIngestedDocumentsRoute: ApiAdminIngestedDocumentsRoute,
  ApiAdminUploadKnowledgeRoute: ApiAdminUploadKnowledgeRoute,
  ApiAnalyticsUsageRoute: ApiAnalyticsUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
