/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiWorkerUploadAttachmentPrepareRouteImport } from './routes/api/worker/upload-attachment-prepare'
import { Route as ApiWorkerUploadAttachmentRouteImport } from './routes/api/worker/upload-attachment'
import { Route as ApiWorkerAttachmentDownloadRouteImport } from './routes/api/worker/attachment-download'
import { Route as ApiInternalGenerateActionPlanRouteImport } from './routes/api/internal/generate-action-plan'
import { Route as ApiAnalyticsUsageRouteImport } from './routes/api/analytics/usage'
import { Route as ApiAdminUploadKnowledgePrepareRouteImport } from './routes/api/admin/upload-knowledge-prepare'
import { Route as ApiAdminUploadKnowledgeRouteImport } from './routes/api/admin/upload-knowledge'
import { Route as ApiAdminIngestedDocumentsRouteImport } from './routes/api/admin/ingested-documents'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerUploadAttachmentPrepareRoute =
  ApiWorkerUploadAttachmentPrepareRouteImport.update({
    id: '/api/worker/upload-attachment-prepare',
    path: '/api/worker/upload-attachment-prepare',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkerUploadAttachmentRoute =
  ApiWorkerUploadAttachmentRouteImport.update({
    id: '/api/worker/upload-attachment',
    path: '/api/worker/upload-attachment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkerAttachmentDownloadRoute =
  ApiWorkerAttachmentDownloadRouteImport.update({
    id: '/api/worker/attachment-download',
    path: '/api/worker/attachment-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalGenerateActionPlanRoute =
  ApiInternalGenerateActionPlanRouteImport.update({
    id: '/api/internal/generate-action-plan',
    path: '/api/internal/generate-action-plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyticsUsageRoute = ApiAnalyticsUsageRouteImport.update({
  id: '/api/analytics/usage',
  path: '/api/analytics/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadKnowledgePrepareRoute =
  ApiAdminUploadKnowledgePrepareRouteImport.update({
    id: '/api/admin/upload-knowledge-prepare',
    path: '/api/admin/upload-knowledge-prepare',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUploadKnowledgeRoute = ApiAdminUploadKnowledgeRouteImport.update({
  id: '/api/admin/upload-knowledge',
  path: '/api/admin/upload-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIngestedDocumentsRoute =
  ApiAdminIngestedDocumentsRouteImport.update({
    id: '/api/admin/ingested-documents',
    path: '/api/admin/ingested-documents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/worker': typeof WorkerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/admin/ingested-documents': typeof ApiAdminIngestedDocumentsRoute
  '/api/admin/upload-knowledge': typeof ApiAdminUploadKnowledgeRoute
  '/api/admin/upload-knowledge-prepare': typeof ApiAdminUploadKnowledgePrepareRoute
  '/api/analytics/usage': typeof ApiAnalyticsUsageRoute
  '/api/internal/generate-action-plan': typeof ApiInternalGenerateActionPlanRoute
  '/api/worker/attachment-download': typeof ApiWorkerAttachmentDownloadRoute
  '/api/worker/upload-attachment': typeof ApiWorkerUploadAttachmentRoute
  '/api/worker/upload-attachment-prepare': typeof ApiWorkerUploadAttachmentPrepareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/worker': typeof WorkerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/admin/ingested-documents': typeof ApiAdminIngestedDocumentsRoute
  '/api/admin/upload-knowledge': typeof ApiAdminUploadKnowledgeRoute
  '/api/admin/upload-knowledge-prepare': typeof ApiAdminUploadKnowledgePrepareRoute
  '/api/analytics/usage': typeof ApiAnalyticsUsageRoute
  '/api/internal/generate-action-plan': typeof ApiInternalGenerateActionPlanRoute
  '/api/worker/attachment-download': typeof ApiWorkerAttachmentDownloadRoute
  '/api/worker/upload-attachment': typeof ApiWorkerUploadAttachmentRoute
  '/api/worker/upload-attachment-prepare': typeof ApiWorkerUploadAttachmentPrepareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manager': typeof ManagerRoute
  '/worker': typeof WorkerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/admin/ingested-documents': typeof ApiAdminIngestedDocumentsRoute
  '/api/admin/upload-knowledge': typeof ApiAdminUploadKnowledgeRoute
  '/api/admin/upload-knowledge-prepare': typeof ApiAdminUploadKnowledgePrepareRoute
  '/api/analytics/usage': typeof ApiAnalyticsUsageRoute
  '/api/internal/generate-action-plan': typeof ApiInternalGenerateActionPlanRoute
  '/api/worker/attachment-download': typeof ApiWorkerAttachmentDownloadRoute
  '/api/worker/upload-attachment': typeof ApiWorkerUploadAttachmentRoute
  '/api/worker/upload-attachment-prepare': typeof ApiWorkerUploadAttachmentPrepareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manager'
    | '/worker'
    | '/api/chat'
    | '/api/admin/ingested-documents'
    | '/api/admin/upload-knowledge'
    | '/api/admin/upload-knowledge-prepare'
    | '/api/analytics/usage'
    | '/api/internal/generate-action-plan'
    | '/api/worker/attachment-download'
    | '/api/worker/upload-attachment'
    | '/api/worker/upload-attachment-prepare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manager'
    | '/worker'
    | '/api/chat'
    | '/api/admin/ingested-documents'
    | '/api/admin/upload-knowledge'
    | '/api/admin/upload-knowledge-prepare'
    | '/api/analytics/usage'
    | '/api/internal/generate-action-plan'
    | '/api/worker/attachment-download'
    | '/api/worker/upload-attachment'
    | '/api/worker/upload-attachment-prepare'
  id:
    | '__root__'
    | '/'
    | '/manager'
    | '/worker'
    | '/api/chat'
    | '/api/admin/ingested-documents'
    | '/api/admin/upload-knowledge'
    | '/api/admin/upload-knowledge-prepare'
    | '/api/analytics/usage'
    | '/api/internal/generate-action-plan'
    | '/api/worker/attachment-download'
    | '/api/worker/upload-attachment'
    | '/api/worker/upload-attachment-prepare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagerRoute: typeof ManagerRoute
  WorkerRoute: typeof WorkerRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAdminIngestedDocumentsRoute: typeof ApiAdminIngestedDocumentsRoute
  ApiAdminUploadKnowledgeRoute: typeof ApiAdminUploadKnowledgeRoute
  ApiAdminUploadKnowledgePrepareRoute: typeof ApiAdminUploadKnowledgePrepareRoute
  ApiAnalyticsUsageRoute: typeof ApiAnalyticsUsageRoute
  ApiInternalGenerateActionPlanRoute: typeof ApiInternalGenerateActionPlanRoute
  ApiWorkerAttachmentDownloadRoute: typeof ApiWorkerAttachmentDownloadRoute
  ApiWorkerUploadAttachmentRoute: typeof ApiWorkerUploadAttachmentRoute
  ApiWorkerUploadAttachmentPrepareRoute: typeof ApiWorkerUploadAttachmentPrepareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/upload-attachment-prepare': {
      id: '/api/worker/upload-attachment-prepare'
      path: '/api/worker/upload-attachment-prepare'
      fullPath: '/api/worker/upload-attachment-prepare'
      preLoaderRoute: typeof ApiWorkerUploadAttachmentPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/upload-attachment': {
      id: '/api/worker/upload-attachment'
      path: '/api/worker/upload-attachment'
      fullPath: '/api/worker/upload-attachment'
      preLoaderRoute: typeof ApiWorkerUploadAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/attachment-download': {
      id: '/api/worker/attachment-download'
      path: '/api/worker/attachment-download'
      fullPath: '/api/worker/attachment-download'
      preLoaderRoute: typeof ApiWorkerAttachmentDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/generate-action-plan': {
      id: '/api/internal/generate-action-plan'
      path: '/api/internal/generate-action-plan'
      fullPath: '/api/internal/generate-action-plan'
      preLoaderRoute: typeof ApiInternalGenerateActionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/usage': {
      id: '/api/analytics/usage'
      path: '/api/analytics/usage'
      fullPath: '/api/analytics/usage'
      preLoaderRoute: typeof ApiAnalyticsUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-knowledge-prepare': {
      id: '/api/admin/upload-knowledge-prepare'
      path: '/api/admin/upload-knowledge-prepare'
      fullPath: '/api/admin/upload-knowledge-prepare'
      preLoaderRoute: typeof ApiAdminUploadKnowledgePrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-knowledge': {
      id: '/api/admin/upload-knowledge'
      path: '/api/admin/upload-knowledge'
      fullPath: '/api/admin/upload-knowledge'
      preLoaderRoute: typeof ApiAdminUploadKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ingested-documents': {
      id: '/api/admin/ingested-documents'
      path: '/api/admin/ingested-documents'
      fullPath: '/api/admin/ingested-documents'
      preLoaderRoute: typeof ApiAdminIngestedDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagerRoute: ManagerRoute,
  WorkerRoute: WorkerRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAdminIngestedDocumentsRoute: ApiAdminIngestedDocumentsRoute,
  ApiAdminUploadKnowledgeRoute: ApiAdminUploadKnowledgeRoute,
  ApiAdminUploadKnowledgePrepareRoute: ApiAdminUploadKnowledgePrepareRoute,
  ApiAnalyticsUsageRoute: ApiAnalyticsUsageRoute,
  ApiInternalGenerateActionPlanRoute: ApiInternalGenerateActionPlanRoute,
  ApiWorkerAttachmentDownloadRoute: ApiWorkerAttachmentDownloadRoute,
  ApiWorkerUploadAttachmentRoute: ApiWorkerUploadAttachmentRoute,
  ApiWorkerUploadAttachmentPrepareRoute: ApiWorkerUploadAttachmentPrepareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
